### ISSUE TITLE
Expose SD Card

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Rev_E_Hardware#18]
### Options
1. Bump in the case and move the battery back

![image](https://user-images.githubusercontent.com/42774675/121413272-85309200-c933-11eb-897b-f520a85019c1.png)

2. Place a 18650 to the side

![image](https://user-images.githubusercontent.com/42774675/121413387-a09b9d00-c933-11eb-9d12-cf3a89e61039.png)

**Comment by chipaudette** [comment]
Are there easily-obtained cylindrical cells that are narrower than the 18650?  Like, are 14500 readily available?  https://en.wikipedia.org/wiki/List_of_battery_sizes#Cylindrical_lithium-ion_rechargeable_battery

[Edit : while this is still a valid question for other sizes, I see that a single 14500 has a capacity of only 850 mA-hrs.  Bummer.]

**Comment by eyuan-creare** [comment]
Fenix is a popular brand among flashlight enthusiasts, so I believe it's 1600mAh rating .  However it is unlikely we will find an off the shelf battery with **leads**.  I just don't like widening the case, even if it is less overall volume.

https://www.batteryjunction.com/fenix-arb-l14-1600u.html

**Comment by biomurph** [comment]
We have two issue threads covering this problem.
@eyuan-creare @chipaudette 
I have put candidates on the other thread for flat pack and cylinder battery options to review.

**Comment by eyuan-creare** [comment]
@chipaudette, @biomurph I'd like to rule out a battery on the side.  I think it makes the case too awkward to put in your pocket and prefer making the case jog in to expose the SD card.  Do you agree?  Should we move forward with option 1?

**Comment by biomurph** [comment]
I would also prefer not to have the battery on the side.
If one of the candidates from the other thread will work, and fit to allow access to the SD card, then awesome!

**Comment by chipaudette** [comment]
The jog in the case is not my favorite (it makes my mind think about our not-so-attractive RevC case) but if everyone else has reservations with the side battery, let's assume that we'll do the jogged case.

Before we fully commit, let's take the next few steps in the design process: 
  1) pick a candidate battery and insert it into the model
  2) conceptually decide where our fasteners will go to ensure that there is space
  3) illustrate the new SD slot and so that we see how easy/hard it might be to access the card

**Comment by chipaudette** [comment]
I do have concerns over the difficulty of getting the SD card in and out (hence my request in bullet 3 above).  

As currently drawn, the jogged wall really blocks your fingers from holding the SD card as you try to slide the card in/out.

![Picture2](https://user-images.githubusercontent.com/1806494/121551716-deed9680-c9dd-11eb-99f3-36b82987b162.jpg)

This is the kind of access issue that I'm looking for ideas on.

**Comment by eyuan-creare** [comment]
Also, it can be difficult to guide the card into the slot without some support.  And adding support to the case can be difficult depending on whether PCBs need to slip past the support to be installed.

Here are some options for exposing the card:

1. We let the SD card stick out a bit and create an indentation for your fingernails or tweezers to get in there

2. _[Thrown out]: 18650 cell on the side_ 

3. We make a false cover that clips in. If we are feeling adventurous, we could make it flip out on a living hinge.  That would retain the original look somewhat but is a bit of a design effort and limits material choices.

![image](https://user-images.githubusercontent.com/42774675/121560960-0c3e4280-c9e6-11eb-8277-eebdf1dc006a.png)

4. SD Card Holder

![image](https://user-images.githubusercontent.com/42774675/121563094-1a8d5e00-c9e8-11eb-8bfb-f7018bc20874.png)



PDF to scale: 
[case_ideas (1).pdf](https://github.com/Tympan/Tympan_Rev_E_Hardware/files/6633038/case_ideas.1.pdf)


@biomurph What kind of materials can you print, and what colors can you do?

**Comment by chipaudette** [comment]
If you're proposing the 2000 mA-hr, where do the fasteners down there fit?  Or are you saying we don't need fasteners down there?

Also, I'm holding a 2000 mA-hr battery in my hand along with a T4.1  The body of the battery is the length of the T4.1, as you've drawn.  But, you need some room for the battery's cable to exit the battery and turn to the side.  To my eye, we need 4-5mm.  Is that extra space requirement enough to break these ideas?  If so, is the 1200 mA-hr any shorter?

**Comment by eyuan-creare** [comment]
@chipaudette: Both the Adafruit 2000mAh and 1200mAh are 2.4" in length.

For option 1, If we need to we can lengthen the case to clear the battery wires and make a large indention for the USB plug.  It will take some effort to mock up so we should choose which design you like best (given the risk of more complex designs) and run with it till it breaks.

**Comment by biomurph** [comment]
I want to make this happen with as little adventure as possible. The case print files should be easy for anyone to print on their own.

I have a Tax mini 2, and it rocks PLA all day! Any color

**Comment by biomurph** [comment]
Also, @eyuan-creare you're only showing the side view. We may get a better sense of access with a view from the short end?

I don't mind a cut away that is kind of like the Rev C, personally. But again, if it can be easy (in quotes).

The lipos that I have listed in the other thread are preferred because they are accessible and affordable.please use dima from those only

**Comment by eyuan-creare** [comment]
Here is another option, though I am doubtful that we can source a battery narrow enough to fit between the headers.  We would likely drop in capacity quite a bit to make this happen.

**Sorry this is what I meant to show**

![image](https://user-images.githubusercontent.com/42774675/121705089-5684f980-caa2-11eb-88d8-6385e0e5d36c.png)

**Comment by eyuan-creare** [comment]
Here's a view of the existing case looking into the audio jacks.  Pink is the SD card.  I also updated the scale drawing.
[2021-0610-01_case_ideas.pdf](https://github.com/Tympan/Tympan_Rev_E_Hardware/files/6633821/2021-0610-01_case_ideas.pdf)


![image](https://user-images.githubusercontent.com/42774675/121582776-672f6400-c9fd-11eb-937a-8f4752625749.png)

**Comment by biomurph** [comment]
@eyuan-creare  I did think about between the headers and we can def get batteries that fit but I have not found one with enough capacity

**Comment by eyuan-creare** [comment]
@chipaudette You asked about locating screws.  I had to do a workaround for the last revision too, where the heat set inserts are above the battery.

![image](https://user-images.githubusercontent.com/42774675/121692868-87f7c800-ca96-11eb-910b-9b753b885e36.png)

For the single screw near the USB connector, we would need to do something similar.  _Shown is the existing design, before moving the battery_.

![image](https://user-images.githubusercontent.com/42774675/121693361-0f453b80-ca97-11eb-8cdc-a849142a2a50.png)

Since Joel will be printing them, it gives us a chance to do more iterations.  We could consider a snap fit case, depending on how elastic the PLA material is.

**Comment by biomurph** [comment]
I have found that I get a nice tight for with the forms from RevD. If you can look at those models in the Rev D repo, the way the cases fit comes out good on my machine.

I would avoid a fit that relies on the plastic unless it is robust clip on one end and screw on the other? Snap fit becomes break fit after a while.

I do want to use the threaded inserts on this build. They are nice

**Comment by biomurph** [comment]
I've just looked around and it seems that PET or PETG would be a good material instead of the PLA.
I think that for the near term, I will use PLA because I have yield from my printer, and then transition to the PETG when there's time to tweak and twiddle the print settings. I have read that it will print as easily as PLA, but getting there can be a bit of a climb. Also, there may be issues with support removal and 'stringing', that is, stringy strings around the part left during print head moves. All of this sounds like it can be overcome and prints will come out good, but for our close deadlines I want to use what I know works. 

When I get a more UV resistant material, I will can send out replacement cases

**Comment by eyuan-creare** [comment]
Perhaps this is a combination of practical and shapely.  There would only be two screws to access the SD card.  It's possible we could make the bottom half snap fit onto the top, with screw holes in case you wanted it to be more secure.

@chipaudette, @biomurph  if you have time today, perhaps we should all chat.  My schedule is pretty free.

Whoops, this is what I meant:

![image](https://user-images.githubusercontent.com/42774675/121713019-5f79c900-caaa-11eb-9dd2-bedb19d57884.png)

**Comment by biomurph** [comment]
I will be able to be on the phone later today.

I think that the idea of a 'hook' or 'tab-slot' type capture on the USB end, while having a screw on the jack end could be nice.

Are you now thinking that we *won't* be putting a slot for the SD and that it will be accessed via case removal?
This would be good *if* we can get the SD card playback working, is that correct?

Also, if we can use the case features to capture the board down by the USB connector, maybe we don't need a screw there?

**Comment by eyuan-creare** [comment]
The idea behind (7) is that the bottom would be easily removeable, by snap fit to the top or perhaps sliding in, or screws.  That way a user could easily access the SD card or swap a battery. It will take some geometry acrobatics to make it happen.  If I have trouble, then I could revert to a snap in cap (3) which would be a 3pc design. 

If we wanted the SD card more accessible, then I think a bump out like (1) or (4) would work.

**Comment by biomurph** [comment]
OK!

I am all for whatever is going to be the most easiest to model, print, assemble, etc.
If it's a removable bottom to get the SD card out and option to swap battery, that's kinda cool!

I have had some luck myslef with a 'one end latch, the other end screw' design. That might be the easiest.

**Comment by chipaudette** [comment]
SD Playback (if you're referring to the bug identified by our friends in Montreal) is unrelated to the need to physically access the SD card.  They are separate issues.

What would relieve our need for physical access is if the MTP functionality were to suddenly be much more mature and if it were part of the Teensyduino install.  MTP lets you electronically access the SD card through the Tympan from your PC.  It basically turns your Tympan into an SD reader such that you never need to physically remove the SD.  

Unfortunately, MTP is neither mature enough nor part of the Teensyduino installation, so having physical access to the SD still seems important.

**Comment by chipaudette** [comment]
@eyuan-creare , I am open to using screws (concept 7).  Looking back at Concept 1, I see that your rendering of Concept 4 actually addresses most of my concerns about getting your fingers / tweezers onto the SD card.  

![Compare1and4](https://user-images.githubusercontent.com/1806494/121729922-049d9d00-cabd-11eb-8717-26ff6280c1f7.jpg)

The part of Concept 4 that is the crucial difference from Concept 1 is that you have raised that upper wall to get it a bit more out of the way of the SD slot.  To me, that seems like enough of a shift to make it workable, even without the SD holder.

What do y'all think of modifying Concept 1 to have the higher wall of Concept 4 (but otherwise staying as Concept 1)??

If it were to work for you, then we'd "just" have to figure out how to do the fasteners (and/or hook) and how to make room for the lead wires to come off the battery.

**Comment by eyuan-creare** [comment]
Yes, there shouldn't be a problem raising that wall.  That 3-pin header between the audio jacks shouldn't be there in a production unit.  Though we may want to leave a wall so that the SD card slides against something.  The tip of the SD card has an edge to it that could allow a screwdriver or pick to flick it out.

**Comment by eyuan-creare** [comment]
Closing this, as we decided on an approach.  I'll follow up with updates on #15
