### ISSUE TITLE
Add ability to disconnect the battery for shipping

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Rev_E_Hardware#6]
For federal regulations for shipping lithium batteries, refer to [49 CFR 173.185(e)](https://www.phmsa.dot.gov/lithiumbatteries).  Also look into regulations from UPS and FedEx.

* Here is a [reference design for shipping Li-Ion batteries from TI](https://www.ti.com/lit/an/slva821/slva821.pdf?ts=1593441515767) based on a momentary push button and a load switch:
<img src ="https://user-images.githubusercontent.com/42774675/86019876-2eb59680-b9f5-11ea-99a4-6382203da33b.png" height =100/>.  It is also mentioned [here](https://e2e.ti.com/blogs_/archives/b/fullycharged/archive/2016/12/27/don-t-let-your-battery-drain-on-the-shelf-use-ship-mode).

* Some charger ICs also have ship mode, such as the [LTC4071 ](https://www.analog.com/media/en/technical-documentation/product-selector-card/2PB_4071.pdf).  This IC disconnects the battery when VBat drops below a threshold voltage.  (This provides the added benefit of handling brownouts.) 

* A battery management IC ([PF1550](https://www.nxp.com/docs/en/data-sheet/PF1550.pdf)) that enters ship mode via I2C, and exits ship mode when a charging voltage is present

* Another battery charger with ship mode ([STBC02](https://www.st.com/resource/en/datasheet/stbc02.pdf))

* Another charger with ship mode: [DA9070](https://www.dialog-semiconductor.com/sites/default/files/da9070_final_datasheet.pdf).  This can enter ship mode via I2C (delaying the battery disconnect until after power if removed).  Exits ship mode when input power is restored.

* Another charger with ship mode [ISL9241](https://www.renesas.com/us/en/doc/datasheet/isl9241.pdf): Enter ship mode via register.  Exit ship mode by connecting power.

**Comment by eyuan-creare** [comment]
* If the battery was a button-top, then you could insert a small strip of plastic as the disconnect.
<img src = "https://user-images.githubusercontent.com/42774675/86017595-358eda00-b9f2-11ea-8051-43f898f637d7.png" height =100/>

*Or, we can place a small strip of plastic on an RTC battery that prevents it from going out of ship mode.

**Comment by eyuan-creare** [comment]
@chipaudette We could either replace the battery charger IC or add a load switch with ship mode.  Ideally, the design would not require a momentary on/off button.

If you like these option, I can mock up a design to pass by Ray.  I like the fact that there are reference designs we can point to.

**Comment by biomurph** [comment]
@eyuan-creare I"m not sure if we need this kind of feature. We ship with a low capacity LiPo (500mAh) and I have found that if you are shipping them contained in equipment. Check out the end of page 4 on this [doc](https://www.ups.com/assets/resources/media/en_US/pack_ship_batteries.pdf). I don't think that we need to worry about Tympan due to the small battery size. Once you get into bigger battery capacity, that's when there may be question, but it seems the cutoff is pretty clear.

(unsure why I'm just seeing this, will check my settings)

**Comment by erk1313** [comment]
@biomurph There's a whole range of regulations for shipping Li-ion batteries (ITAA, Federal CFR, Shipper (UPS/FedEx Air or Ground).  I have a summary I can share at some later point. 
 If it weren't for the fact that we qualify as a low-production prototype, we would require UN38.1 testing for the completed assembly.  I'll be reviewing how Creare interprets these regulations with Creare's safety person in August and will check back then.  Their initial ruling was that a physical disconnect was required, but I think that is too conservative a ruling.

**Comment by biomurph** [comment]
Sounds good, @eyuan-creare 
My research has only gone as deep as UPS and DHL.

**Comment by eyuan-creare** [comment]
After a review by Creare's safety team, the Rev-D design was deemed safe for shipping with the battery connected, with these three design changes:
* Place the fuse immediately after the battery
* Move the power switch before the voltage regulators

Notes contained on networked folder: \\OLYMPUS\Projects\7146-Cool-Aid\Technical Work\Design\2020-0710_Shipping Lithium Batteries

![image](https://user-images.githubusercontent.com/42774675/92526856-20a1a480-f1f4-11ea-94cb-3772a3e3808d.png)

**Comment by biomurph** [comment]
@erk1313 
I can make those changes to the Rev E prototype design.

**Comment by chipaudette** [comment]
@biomurph 
Was this change fully implemented in Rev E?  

Looking at the current RevE schem, I think that I see that the switch has been moved (great!), but I don't think that the fuze is as early in the circuit as is shown here in the figure above.  In the figure above, it's immediately after the battery.  But it appears to be after the switch in the current RevE schem...

**Comment by biomurph** [comment]
@chipaudette Changes done on my local. Will push to repo.

**Comment by biomurph** [comment]
Just for the sake of clarity on this. The resoning we had in the beginning to arrange the power supply this way was to make sure that the RTC [V-BAT] was powered by the 3.3V. We gave users the option to add their own external power for the V-BAT. In order to do this, when the Tympan D was 'off', there was power going to the RTC only, so the 3.3V reg was running to do that when the switch was 'off'. In this new version, we are adding a coin cell to power the RTC, so we don't need to run the LiPo to do that work. That's why in previous the switch was after the Vreg.
